### ISSUE TITLE
some questions about code

### ISSUE THREAD

**Issue by xmu-chen** [zmzhang/airPLS#1]
1.what is the use of  i on line 50？
2.How to adjust itermax？

**Comment by zmzhang** [comment]
@xmu-chen 

> 1.what is the use of i on line 50？

The[ i on line 50](https://github.com/zmzhang/airPLS/blob/17a61e252b601bd934d43a142c9bb68641ae7112/airPLS.py#L50) is not used in further code.
You can just remove it.

> 2.How to adjust itermax？

There is no need to adjust itermax in most cases, since airPLS converges very fast
