### ISSUE TITLE
n=1的光谱报错，数组类型是1701x1  double  第35行矩阵维度必须一致

### ISSUE THREAD

**Issue by omaiyiwa** [zmzhang/airPLS#4]

**Comment by zmzhang** [comment]
@omaiyiwa ，谢谢你的反馈!
在输入矩阵中，行（row）为样本，列（column）为信号的检测通道。
请将光谱进行转置处理，将其变为1x1701的矩阵，应该可以解决问题。

请参考：
https://github.com/zmzhang/airPLS/blob/1f1321ba0f0d1f01e1c453ab5963350aa3dd12bc/airPLS.m#L4
