### ISSUE TITLE
Question about Python implementation

### ISSUE THREAD

**Issue by mullinix** [zmzhang/airPLS#6]
The array edge value is determined by [line 82](https://github.com/zmzhang/airPLS/blob/9b0a9a7b1209c316c9eadc76f1acac9e5ca27049/airPLS.py#L82) in the Python implementation.

It occurred to me that this expression is taking the maximum of negative values `d[d<0].max()` which will likely be close to `0` in most cases... resulting in the exponential evaluating to `1`.

If this **is not** the intention, should the algorithm be updated to the max of the absolute of the negative values (i.e. `d[d<0].abs().max()`)?

If this **is** the intention, can we just save the effort and set the value to `1`? The difference between `1` and `very close to 1` doesn't seem worth the computation here...

**Comment by zmzhang** [comment]
@mullinix 
Thanks for your feedback.
We can use the asymmetry parameter for the boundaries like MATLAB version.
https://github.com/zmzhang/airPLS/blob/9b0a9a7b1209c316c9eadc76f1acac9e5ca27049/airPLS.m#L64

Any related pull requests are welcomed!
