### ISSUE TITLE
基线问题

### ISSUE THREAD

**Issue by guishilike** [zmzhang/airPLS#7]
关于airPLS,我有几个问题想要请教一下：
（1）如果谱图中出现一个下降曲线，在去除基线后会形成为一个峰，这种情况该如何解决？
![image](https://user-images.githubusercontent.com/51023060/167396948-365e294f-de44-4906-9157-b3ca73da3f42.png)
（2）有些平缓区域的基线消除不够，该如何调整？
![image](https://user-images.githubusercontent.com/51023060/167397054-3987fa4a-500a-40ef-999a-d1bf7ae0829d.png)

**Comment by zmzhang** [comment]
Hi, @guishilike ,

(1) Irregular baseline.
The common baseline in Raman spectra is relatively flat and can therefore be fitted with a weighted Whittaker smoother.
This special and irregular baselines need special treatment. For example, these interval weights can be forced to be set to 1.

(2) Flat region.
You can choose porder=1 and also optimize the lambda parameter for more flexibility in baseline fitting.


I hope these suggestions can solve your problem. Feel free to submit pull requests.
